language: node_js
node_js:
 — node

before_script:
  - npm install
  - npm install -g firebase-tools
  - npm install -g ionic@latest
  - npm install protractor --save-dev
  - npm install -g webdriver-manager
  - webdriver-manager update
  - npm install jasmine --save-dev
  - npm install jasmine-spec-reporter --save-dev
  - npm install ts-node --save-dev
  - npm install connect --save-dev
  - npm install @types/jasmine --save-dev
  - npm install @types/node --save-dev

script:
  - ionic-app-scripts build  
  - selenium-standalone start
  - ionic serve
  - protractor e2e/conf.js
  
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive


notifications:
  email:
    recipients:
      - laura.meyer@hs-furtwangen.de
      - m.schilling@hs-furtwangen.de
      - inna.beierbach@hs-furtwangen.de
      - paul.dederer@hs-furtwangen.de
    on_success: always
    on_failure: always
