language: node_js
node_js:
 — node

before_script:
  - npm install
  - npm install -g firebase-tools
  - npm install -g ionic@latest

script:
 — ionic cordova build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - laura.meyer@hs-furtwangen.de
      - michael.schilling@hs-furtwangen.de
      - inna.beierbach@hs-furtwangen.de
    on_success: never
    on_failure: always
