language: node_js
node_js:
 — node

 branches:
 only:
 — master

before_script:
  - npm install
  - npm install -g firebase-tools
  - npm install -g ionic@latest

script:
 — ionic cordova build browser — prod

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

 on:
   branch: master
 local_dir: www

notifications:
  email:
    recipients:
      - laura.meyer@hs-furtwangen.de
      - michael.schilling@hs-furtwangen.de
      - inna.beierbach@hs-furtwangen.de
    on_success: never
    on_failure: always
