language: node_js
node_js:
 — node

before_script:
  - npm install
  - npm install -g firebase-tools
  - npm install -g ionic@latest

script:
  - ionic-app-scripts build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive


notifications:
  email:
    recipients:
      - laura.meyer@hs-furtwangen.de
      - michael.schilling@hs-furtwangen.de
      - inna.beierbach@hs-furtwangen.de
    on_success: never
    on_failure: always
